# This is a basic workflow to help you get started with Actions

name: packages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    branches: [ master ]
    paths-ignore:
      - README.md
      - LICENSE

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Set node version
    #    strategy:
    #      matrix:
    #        node-version: [8.x, 10.x, 12.x, 13.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up node version@13.x
        uses: actions/setup-node@v1
        with:
          #        node-version: ${{ matrix.node-version }}
          node-version: '13.x'

      - name: Install dependencies
        run: npm install

      - name: Run eslint
        run: npm run lint --fix

      - name: Clean lerna parallel
        run: npm run clean

      - name: Build packages
        run: npm run build