name: publish
on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - LICENSE
      - build.yaml
      - release.yaml
  pull_request:
    branches: [ master ]
    types: [ closed ]
    paths-ignore:
      - README.md
      - LICENSE
      - build.yaml
      - release.yaml

env:
  CI: true
jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: 13
          registry-url: 'https://registry.npmjs.org'
      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: yarn install

      - name: Check eslint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Check updated
        run: yarn check

      - name: Publish
        run: yarn pub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}